# Generated by Django 5.0.1 on 2024-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_remove_lawyer_identification_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer_identification",
            name="adresse",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="adresse_continue",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="barreau",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="codepostale",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="langue",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="raisonsociale",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="siren",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="specialite",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="ville",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
