# Generated by Django 5.0.1 on 2024-04-11 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_lawyer_identification_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer_identification",
            name="dateserment",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
