# Generated by Django 5.0.1 on 2024-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_alter_lawyer_identification_dateserment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawyer_identification",
            name="certfication",
        ),
        migrations.AddField(
            model_name="lawyer_identification",
            name="surname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lawyer_identification",
            name="dateserment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
