# Generated by Django 5.0.1 on 2024-02-27 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pratique", "Question pratique"),
                            ("droit", "Question de droit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("constitutionnel", "Droit constitutionnel"),
                            ("administratif", "Droit administratif"),
                            ("fiscal", "Droit fiscal"),
                            ("pénal", "Le droit pénal et procédure pénale"),
                            ("judiciaire", "Droit judiciaire"),
                            ("civil", "Droit civil"),
                            ("commercial", "Droit commercial"),
                            ("social", "Droit social"),
                            (
                                "sécurité_sociale",
                                "Droit de la sécurité sociale et droit international privé",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=3000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("resolue", "Résolue"),
                            ("ferme", "Fermé"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("votes", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Blog.question"
                    ),
                ),
            ],
        ),
    ]
